New data
markovmodel/PyEMMA pull request #1097
Opened 2017-05-19 22:44 UTC by cwehmeyer

Added a generator for multi-ensemble data.

2017-05-19 22:51 UTC, marscher commented on doc/source/CHANGELOG.rst
> +   - added a multi-ensemble data generator for the 1D asymmetric double well.
please add the number of this PR here.

2017-05-19 22:53 UTC, cwehmeyer commented on doc/source/CHANGELOG.rst
> +   - added a multi-ensemble data generator for the 1D asymmetric double well.
done

2017-05-19 22:57 UTC, marscher requested changes
Could you please add a simple invocation of this, to see it does not fail? Actually I trust you that you've tested this well, but if somebody is going to change (break) it in the future, we have no chance to catch this early.

Put it in datasets.tests.test_datasets.

2017-05-20 00:21 UTC, marscher approved these changes
perfect!

2017-05-20 00:22 UTC, marscher commented
I just cancelled the second appveyor job (there is no need to test both the branch and the PR merge to devel in this case).

2017-05-20 00:23 UTC, merged